export const CARD_NAME = 'CARD_NAME';
export const CARD_NUMBER = 'CARD_NUMBER';
export const CARD_MOUTH = 'CARD_MOUTH';
export const CARD_YEAR = 'CARD_YEAR';
export const CARD_CVC = 'CARD_CVC';
export const RESET_CARD = 'RESET_CARD';

export const CARD_NAME_SUCCESS = 'CARD_NAME_SUCCESS';
export const CARD_NUMBER_SUCCESS = 'CARD_NUMBER_SUCCESS';
export const CARD_MOUTH_SUCCESS = 'CARD_MOUTH_SUCCESS';
export const CARD_YEAR_SUCCESS = 'CARD_YEAR_SUCCESS';
export const CARD_CVC_SUCCESS = 'CARD_CVC_SUCCESS';
export const RESET_CARD_SUCCESS = 'RESET_CARD_SUCCESS';

export const CARD_NAME_ERROR = 'CARD_NAME_ERROR';
export const CARD_NUMBER_ERROR = 'CARD_NUMBER_ERROR';
export const CARD_DATE_ERROR = 'CARD_YEAR_ERROR';
export const CARD_CVC_ERROR = 'CARD_CVC_ERROR';

